name: Deptrac Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deptrac:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust PHP version as needed


      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: List files in the working directory
        run: ls -la

      - name: Run phpcs Analysis
        run: |
          php -d memory_limit=512M ./vendor/bin/phpcs --report=json --exclude=Generic.Files.LineLength | tee -a codesniffer.json

      - name: Codesniffer format to SonarCloud
        run: |
          php CodeSnifferToSonarCloud.php

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}