name: Static Analysis

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main  # Change to your main branch if it's different

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Change to your PHP version
          extensions: mbstring, xml, curl, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --no-scripts

      - name: Run Deptrac
        run: |
          echo "Contents of base:"
          ls -la ./*
          php -d memory_limit=512M ./vendor/bin/deptrac analyze --config-file=deptrac.yaml
