name: Deptrac Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deptrac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate diffing

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust PHP version as needed

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Get Changed PHP Files
        id: changed_files
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Base branch is: $BASE_BRANCH"

          # Check for changes in PHP files
          files=$(git diff --name-only "$BASE_BRANCH"..."$GITHUB_SHA" -- '*.php')

          # Output the list of changed files
          if [ -z "$files" ]; then
            echo "No PHP files changed."
            echo "FILES=all" >> $GITHUB_ENV # Set to all if no files
          else
            echo "Changed PHP files: $files"
            echo "FILES=$files" >> $GITHUB_ENV # Set the changed files
          fi

      - name: Run Deptrac Analysis
        run: |
          echo "Running Deptrac analysis..."
          php -d memory_limit=512M ./vendor/bin/deptrac analyze --config-file=deptrac.yml
